### ISSUE TITLE
[Question] Firmware requirements

### ISSUE THREAD

**Issue by hitech95** [rpi-Receiver/si468x_dab_receiver#1]
I have another product that it is using the same IC.
My idea was to plug a RPI into it.

I could try to extract the FW from that device MCU.
But I think that the FWs in it will be missing the AM and the mini boot ones.

Are thoose mandatory?

**Comment by rpi-Receiver** [comment]
What you will need is:
firmware-mini
firmware-patch
and the firmware for the proper mode. If you are not planing to use AM you won't need it.
You can see my Firmwarerevisions in [rpi-receiver-overlay.dts](https://github.com/rpi-Receiver/si468x_dab_receiver/blob/main/rpi-receiver-overlay.dts)
The Firmware could also be stored in an EEPROM instead of the MCU!

**Comment by hitech95** [comment]
After spoofing thei2c bus I've captured two firmware upload transactions.
One is for sure the DAB FW, it is huge like 500KB and the other is like 16KB and I think it is the patch.
Allt he FW seems to start with `10 00 00 ff 00 00 00 00 00 00 00 00 78 56 34`.
But the device is not having the EEPROM... so cant say how big the mini rom is and if it have the same header as the patches.

Unfortunatly FW is under NDA.
Isnt the mini FW used only for some sort of programming/debug? IDK I'm still tring to understand if I have to find a DEV board or something...

**Comment by rpi-Receiver** [comment]
Only the patch starts with the Bytes you mentioned!
mini patch:
`03 00 00 FE 00 00 00 00 00 00 00 00 78 56 34 12`
fmhd:
`01 00 00 00 00 00 00 00 00 00 00 00 78 56 34 12`
dab:
`01 00 00 00 00 00 00 00 00 00 00 00 78 56 34 12`
amhd:
`3C 42 49 46 5F 48 44 52 5F 53 45 43 54 4E 3E 0A`
at least the Versions I have from the eval board, but I know there are newer ones.

**Comment by hitech95** [comment]
Youre right, my bad,
FW header is for application mode is `01 00 00 00 00 00 00 00 00 00 00 00 78 56 34 12`
Unfortunatly no mini patch during the transaction. For what I've got it is used only for probing on driver init.
Is there a way to make this optional and apply only the rom patch 16?

**Comment by rpi-Receiver** [comment]
As far as I know you will need mini patch, patch and the application.....

**Comment by hitech95** [comment]
I have 2 out of 3. The device is working with its MCU so I'm not sure how at this point.
I don't have anything else to test this with. the Ugreen board seems to be missing th eeprom too. But the CLI cannot be decompiled by license. With an i2c sniffer we could see if the mini patch is applied.

Or maybe ask some one of the developer.

**Comment by rpi-Receiver** [comment]
The document, that guided me most, was [an649](https://www.silabs.com/documents/public/application-notes/an649.pdf) from silabs. Take a look at the flowcharts.

**Comment by hitech95** [comment]
I have checked it, I was wondering if in some sort of wat the mini patch is somehow inc.luded into the patch v16.

**Comment by rpi-Receiver** [comment]
I do not think so, but I never verified.
